version: '3.8'

services:
  json-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data.json:/app/data.json
    environment:
      - NODE_ENV=development
    command: npx json-server --static . --watch data.json --host 0.0.0.0
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3